osx_image: xcode10.2
rvm:
  - 2.6.2
language: objective-c
before_install:
  - gem install cocoapods
  - pod repo update
  - gem install xcpretty slather -N
  - xcrun instruments -w "iPhone 6 (12.2)" || echo "(Pre)Launched the simulator."
cache: cocoapods
podfile: Example/Podfile
script:
  - set -o pipefail && xcodebuild test -workspace example/RPCircularProgressExample.xcworkspace -scheme "RPCircularProgressExample" -destination "platform=iOS Simulator,name=iPhone XS,OS=12.2" -enableCodeCoverage YES ONLY_ACTIVE_ARCH=YES | xcpretty -c
after_success:
  - pod lib lint --allow-warnings
  - slather coverage --ignore "../**/*/Xcode*" --scheme "RPCircularProgressExample" --workspace example/RPCircularProgressExample.xcworkspace example/RPCircularProgressExample.xcodeproj